# Generated by Django 4.2 on 2023-08-10 07:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chat", "0002_alter_record_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="record",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
