# Generated by Django 4.2 on 2023-08-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_alter_record_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="theme",
            field=models.CharField(default="new chat", max_length=30),
        ),
    ]
