# Generated by Django 4.2 on 2023-08-11 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0004_record_theme"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="context",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="record",
            name="answer",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="created_time",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="record",
            name="question",
            field=models.TextField(blank=True),
        ),
    ]
