# Generated by Django 4.2 on 2023-08-15 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0006_topic_conversation"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Record",
        ),
    ]
