# Generated by Django 4.2 on 2023-08-17 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0007_delete_record"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="prompt_audio",
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="conversation",
            name="response_audio",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
