# Generated by Django 4.2 on 2023-08-24 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0008_conversation_prompt_audio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="custom_context",
            field=models.TextField(
                blank=True,
                default="chatGPT Role: You are an oral English teacher fluent in both Chinese and English. The following system content is the former conversation between user and you. Please answer the user's questions in a manner that mimics that of an oral English teacher. Unless specifically requested by the user, the length of each answer should be limited to 125 words.",
            ),
        ),
    ]
