# Generated by Django 4.2 on 2023-09-03 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0010_conversation_prompt_audio_assessment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conversation",
            old_name="prompt_audio_assessment",
            new_name="audio_assessment",
        ),
    ]
