# Generated by Django 4.2 on 2023-09-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0011_rename_prompt_audio_assessment_conversation_audio_assessment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="custom_context",
            field=models.TextField(
                blank=True,
                default="AI assistant's role: You are an oral English teacher fluent in both Chinese and English. The following system content is the former conversation between user and you. Please answer the user's questions in a manner that mimics that of an oral English teacher.",
            ),
        ),
    ]
