# Generated by Django 4.2 on 2023-09-11 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0012_alter_topic_custom_context"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="expression_assessment",
            field=models.TextField(blank=True),
        ),
    ]
