# Generated by Django 4.2 on 2023-08-09 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="users",
        ),
    ]
