# Generated by Django 4.2 on 2023-08-10 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0003_alter_record_user"),
        ("user", "0002_alter_user_table"),
    ]

    operations = [
        migrations.DeleteModel(
            name="User",
        ),
    ]
